// Public operation-domain facade; implementation details stay internal.
export { createAutonomousBattleSimulation } from "./internal/autonomousBattleRuntime";
export type {
  AutonomousBattleActorCondition,
  AutonomousBattleActorDefinition,
  AutonomousBattleActorSnapshot,
  AutonomousBattleDecisionTrace,
  AutonomousBattleDefinition,
  AutonomousBattleEvent,
  AutonomousBattleFormationDefinition,
  AutonomousBattleFormationEntry,
  AutonomousBattleFormationSnapshot,
  AutonomousBattleHarnessConsequence,
  AutonomousBattleHarnessConsequenceCode,
  AutonomousBattleHarnessPolicies,
  AutonomousBattleHarnessSnapshot,
  AutonomousBattleIntervention,
  AutonomousBattleInterventionBudgetSnapshot,
  AutonomousBattleInterventionReceipt,
  AutonomousBattleInterventionResult,
  AutonomousBattleObjectiveDefinition,
  AutonomousBattleObjectiveEvidence,
  AutonomousBattleObjectiveSnapshot,
  AutonomousBattleRecentEvents,
  AutonomousBattleResolution,
  AutonomousBattleSimulation,
  AutonomousBattleSimulationFactory,
  AutonomousBattleSimulationOptions,
  AutonomousBattleSnapshot,
} from "./autonomousBattle";
